##  Assignment :: Analyse butane structure

In [29]:
gro_file = "butane.gro"

In [30]:
gro_file

'butane.gro'

In [31]:
with open(gro_file, 'r') as f:
    lines = f.readlines()

In [60]:
lines

['Butane\n',
 '   14\n',
 '    1BUT     C1    1   1.104   1.205   1.113\n',
 '    1BUT     C2    2   1.186   1.090   1.168\n',
 '    1BUT     H1    3   1.000   1.198   1.149\n',
 '    1BUT     H2    4   1.102   1.204   1.004\n',
 '    1BUT     H3    5   1.143   1.302   1.146\n',
 '    1BUT     C3    6   1.329   1.085   1.113\n',
 '    1BUT     H4    7   1.136   0.996   1.142\n',
 '    1BUT     H5    8   1.188   1.095   1.277\n',
 '    1BUT     C4    9   1.413   1.204   1.155\n',
 '    1BUT     H6   10   1.326   1.079   1.003\n',
 '    1BUT     H7   11   1.377   0.994   1.149\n',
 '    1BUT     H8   12   1.376   1.298   1.112\n',
 '    1BUT     H9   13   1.516   1.191   1.120\n',
 '    1BUT    H10   14   1.415   1.215   1.264\n',
 '   2.51600   2.30820   2.27380\n']

In [32]:
title = lines[0].strip()
n_atoms = int(lines[1].strip())
atom_lines = lines[2:2 + n_atoms]
box_line = lines[-1].strip()

In [33]:
title, n_atoms, atom_lines[:2], box_line

('Butane',
 14,
 ['    1BUT     C1    1   1.104   1.205   1.113\n',
  '    1BUT     C2    2   1.186   1.090   1.168\n'],
 '2.51600   2.30820   2.27380')

In [65]:

c1 = 1.104, 1.205, 1.113
c2 = 1.186, 1.090, 1.168
c3 = 1.329, 1.085, 1.113
c4 = 1.413, 1.204, 1.155

In [66]:
type(c1), type(c2), type(c3), type(c4)

(tuple, tuple, tuple, tuple)

In [67]:
c1,c2,c3, c4

((1.104, 1.205, 1.113),
 (1.186, 1.09, 1.168),
 (1.329, 1.085, 1.113),
 (1.413, 1.204, 1.155))

In [68]:
import math
import numpy as np
distance = math.sqrt((c4[0] - c1[0])**2 + (c4[1] - c1[1])**2 + (c4[2] - c1[2])**2)
print(f"Distance between C1 and C4: {distance:.2f} nm")

Distance between C1 and C4: 0.31 nm


In [69]:
c1 = np.array(c1)
c2 = np.array(c2)
c3 = np.array(c3)
c4 = np.array(c4)

In [70]:
c1, c2, c3, c4

(array([1.104, 1.205, 1.113]),
 array([1.186, 1.09 , 1.168]),
 array([1.329, 1.085, 1.113]),
 array([1.413, 1.204, 1.155]))

In [71]:
type(c1), type(c2), type(c3), type(c4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [38]:
#vector 
p1 = c2 - c1
p2 = c3 - c2
p3 = c4 - c3 

In [ ]:
v1 = np.cross(p1, p2)
v1 = v1 / np.linalg.norm(v1)
v2 = np.cross(p2, p3)
v2 = v2 / np.linalg.norm(v2)

In [40]:
v1,v2

(array([0.30981414, 0.58090151, 0.75270753]),
 array([ 0.29630863, -0.49701271,  0.81558541]))

In [59]:
cos_theta = np.dot(v1, v2)
cos_theta = np.clip(cos_theta, -1.0, 1.0)
angle_rad = np.arccos(cos_theta)
dihedral_deg = np.degrees(angle_rad)
print(f"Dihedral angle between C1-C2-C3-C4: {dihedral_deg:.2f} degrees")


Dihedral angle between C1-C2-C3-C4: 65.36 degrees


In [41]:
angle_rad = np.arccos((v1*v2).sum(-1) / ((v1**2).sum(-1) * (v2**2).sum(-1))**0.5)


In [42]:
angle_rad

1.14067348907885

In [43]:
dihedral_deg = np.degrees(angle_rad)

In [44]:
dihedral_deg

65.3557767266801

In [45]:
n1 = np.cross(p1, p2)
n2 = np.cross(p2, p3)

In [46]:
n1, n2

(array([0.0066  , 0.012375, 0.016035]),
 array([ 0.006335, -0.010626,  0.017437]))

In [47]:
n1_unit = n1 / np.linalg.norm(n1)
n2_unit = n2 / np.linalg.norm(n2)

In [48]:
n1_unit

array([0.30981414, 0.58090151, 0.75270753])

In [49]:
cos_theta = np.dot(n1_unit, n2_unit)

In [50]:
cos_theta

0.41698245456048116

In [51]:
cos_theta = np.clip(cos_theta, -1.0, 1.0)

In [52]:
cos_theta

0.41698245456048116

In [53]:
angle_rad = np.arccos(cos_theta)

In [54]:
angle_rad

1.14067348907885

In [55]:
dihedral_deg = np.degrees(angle_rad)
print(dihedral_deg)

65.3557767266801


In [56]:
# import MDAnalysis as mda

# u = mda.Universe("butane.gro")
# print("Number of atoms:", len(u.atoms))
# print("Number of residues:", len(u.residues))
# print("Box dimensions:", u.dimensions)
# print(u.atoms[:5])

In [ ]:
""" Dihedral angles from coordinates. Get dihedral angles from 
    protein backbone coordinates.
    This script takes 4 vectors representing 4 points as input
    and returns the dihedral angle between them.
    
    The script was originally developed to calculate dihedral angles (phi,psi)
    from protein backbone atoms' coordinates in 3D (N-term, C-alhpa, Cterm).
"""

import numpy as np

def calc_dihedral(u1, u2, u3, u4):
    """ Calculate dihedral angle method. From bioPython.PDB
    (adapted to np.array)
    Calculate the dihedral angle between 4 vectors
    representing 4 connected points. The angle is in
    [-pi, pi].
    """

    a1 = u2 - u1
    a2 = u3 - u2
    a3 = u4 - u3

    v1 = np.cross(a1, a2)
    v1 = v1 / (v1 * v1).sum(-1)**0.5
    v2 = np.cross(a2, a3)
    v2 = v2 / (v2 * v2).sum(-1)**0.5
    porm = np.sign((v1 * a3).sum(-1))
    rad = np.arccos((v1*v2).sum(-1) / ((v1**2).sum(-1) * (v2**2).sum(-1))**0.5)
    if not porm == 0:
        rad = rad * porm

    return rad
    
a = np.array([1219.7, 4106.1, -7366.7])
b = np.array([1277.1, 4016.6, -7447.1])
c = np.array([1398.6, 3944.8, -7407.8])
d = np.array([1501.2, 3943.2, -7521.3])

alpha = calc_dihedral(a,b,c,d)
print("Dihedral angle in radians:", alpha, "and degrees:", alpha*180/np.pi)

In [ ]:
# def get_coordinates(atom_name):
#     for line in atom_lines:
#         atom = line[10:15].strip()
#         if atom == atom_name:
#             x = float(line[20:28].strip())
#             y = float(line[28:36].strip())
#             z = float(line[36:44].strip())
#             return (x, y, z)
#     return None

# c1 = get_coordinates("C1")
# c4 = get_coordinates("C4")